{% set name = "fluidsim-core" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4b7a23649df9d10cde6510280fb8683550549d4cbbc1ebb0bc6adc6e559915f7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
    - flit_core
  run:
    - python >=3.9
    - importlib_metadata
    - fluiddyn >=0.3.2

test:
  imports:
    - fluidsim_core
    - fluidsim_core.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://foss.heptapod.net/fluiddyn/fluidsim
  summary: Pure-Python core library for FluidSim framework
  license: LicenseRef-CeCILL
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - CyrilleBonamy
    - paugier
    - ashwinvis
